### ISSUE TITLE
Remove Proper Nouns

### ISSUE THREAD

**Issue by chimano** [tehblasian/aita#30]
#5

**Comment by chimano** [comment]
## Input
"AITA for naming our kid’s after past cats and not telling my husband", "content" : "Growing up I had about 35 cats throughout the 18 years i lived with my mom(she did rescue and foster work). 3 of those cats were named Samson, Sabrina, and Sonny. I have 2 sons and a daughter. Their middles names are Samson, Sabrina, and Sonny.


When I was pregnant with them my husband didn’t really care about names. He gave his input but didn’t feel strongly about any names, especially middle ones. I suggested these and he agreed they sounded nice. 


The bad part: I didn’t tell him they were the names of my previous cats. I don’t know why. The first 2 I did just think the names sounded good with their first names regardless of my cats being named that. By kid3 came I immediately went to my cats names for inspiration and settled on sonny. My husband liked it but again, I didn’t mention the cats.


Then the other day I mentioned my cat Samson being FIV+(we are looking to adopt a senior FIV kitty). He said “Samson? Please don’t tell me you named our kid after the cat.” He said it in a joking way but I felt the need to “come clean” and told him all of our kids are named after some of my past cats. I told him I wouldn’t have named the kids that if I didn’t genuinely like the names but yeah they are from my past cats.


He wasn’t really mad but he seemed super annoyed and thought it was weird."
## Output
Growing I cat throughout year lived mom rescue foster work cat named I son daughter Their middle name When I pregnant husband really care name He gave input feel strongly name especially middle one I suggested agreed sounded nice The bad part I tell name previous cat I know The first I think name sounded good first name regardless cat named By kid3 came I immediately went cat name inspiration settled sonny My husband liked I mention cat Then day I mentioned cat looking adopt senior kitty He said tell named kid He said joking way I felt need come clean told kid named past cat I told I named kid I genuinely like name yeah past cat He really mad seemed super annoyed thought weird

**Comment by kwreen** [comment]
Resolved in #31
